/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.nuxeo.mule;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.mule.api.ConnectionException;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Connect;
import org.mule.api.annotations.ConnectionIdentifier;
import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Disconnect;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.Transformer;
import org.mule.api.annotations.ValidateConnection;
import org.mule.api.annotations.display.FriendlyName;
import org.mule.api.annotations.display.Password;
import org.mule.api.annotations.display.Placement;
import org.mule.api.annotations.param.ConnectionKey;
import org.mule.api.annotations.param.Default;
import org.mule.api.annotations.param.Optional;
import org.nuxeo.ecm.automation.client.AutomationClient;
import org.nuxeo.ecm.automation.client.OperationRequest;
import org.nuxeo.ecm.automation.client.Session;
import org.nuxeo.ecm.automation.client.adapters.DocumentService;
import org.nuxeo.ecm.automation.client.jaxrs.impl.HttpAutomationClient;
import org.nuxeo.ecm.automation.client.model.DocRef;
import org.nuxeo.ecm.automation.client.model.Document;
import org.nuxeo.ecm.automation.client.model.Documents;
import org.nuxeo.ecm.automation.client.model.FileBlob;
import org.nuxeo.ecm.automation.client.model.OperationDocumentation;
import org.nuxeo.ecm.automation.client.model.OperationDocumentation.Param;
import org.nuxeo.ecm.automation.client.model.PropertyMap;
import org.nuxeo.ecm.automation.client.model.StringBlob;

/**
 * Connector that uses Nuxeo Automation java client to leverage Nuxeo Rest API
 * 
 * @author <a href="mailto:tdelprat@nuxeo.com">Tiry</a>
 * 
 */
@Connector(name = "nuxeo", schemaVersion = "1.0-SNAPSHOT")
public class NuxeoConnector {

    /**
     * Nuxeo Server name (IP or DNS name)
     */
    @Configurable
    @Placement(group = "Connection")
    private String serverName;

    /**
     * Port used to connect to Nuxeo Server
     */
    @Configurable
    @Placement(group = "Connection")
    private String port;

    /**
     * Context Path for Nuxeo instance
     */
    @Configurable
    @Placement(group = "Connection")
    private String contextPath = "nuxeo";

    public NuxeoConnector() {
        serverName = "localhost";
        port = "8080";
        contextPath = "nuxeo";
    }

    /**
     * get Nuxeo Server Name
     * 
     * @return Nuxeo Server Name
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * get Nuxeo Server Port
     * 
     * @return Nuxeo Server Port
     */
    public String getPort() {
        return port;
    }

    /**
     * get Nuxeo Server Context pat
     * 
     * @return Nuxeo Server Context path
     */
    public String getContextPath() {
        return contextPath;
    }

    /**
     * set Nuxeo Server name
     * 
     * @param serverName
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * set port used to connect to Nuxeo Server
     * 
     * @param port
     */
    public void setPort(String port) {
        this.port = port;
    }

    /**
     * set Context path of the target Nuxeo Server
     * 
     * @param contextPath
     */
    public void setContextPath(String contextPath) {
        this.contextPath = contextPath;
    }

    private Session session;

    protected String getServerUrl() {
        return "http://" + serverName + ":" + port + "/" + contextPath
                + "/site/automation";
    }

    protected DocumentService docService;

    /**
     * Connect to Nuxeo Server via Automation java client
     * 
     * @param username Nuxeo user name
     * @param password Nuxeo password
     * @throws ConnectionException
     */
    @Connect
    public void connect(@ConnectionKey
    String username, @Password
    String password) throws ConnectionException {
        AutomationClient client = new HttpAutomationClient(getServerUrl());
        session = client.getSession(username, password);
        docService = session.getAdapter(DocumentService.class);
    }

    /**
     * Disconnect
     */
    @Disconnect
    public void disconnect() {
        if (session != null) {
            session.close();
        }
    }

    /**
     * Are we connected
     * 
     * @return true if an Automation Session is active
     */
    @ValidateConnection
    public boolean isConnected() {
        return (session != null);
    }

    /**
     * Are we connected
     * 
     * @return fake ConnectionId based on serverUrl and username
     */
    @ConnectionIdentifier
    public String connectionId() {
        if (session != null) {
            return getServerUrl() + session.getLogin();
        } else {
            return getServerUrl();
        }
    }

    /**
     * Get a Document from Nuxeo repository
     * 
     * @param docRef the DocumentRef
     * @return a Document Object
     * @throws Exception in case of error
     */
    @Processor
    public Document getDocument(@Placement(group = "operation parameters")
    @FriendlyName("Document Reference (docRef)")
    String docRef) throws Exception {
        return docService.getDocument(docRef);
    }

    /**
     * Get the root Document of Nuxeo Repository
     * 
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document getRootDocument() throws Exception {
        return getDocument("/");
    }

    /**
     * Create a Document
     * 
     * @param parentRef reference of the Parent document
     * @param docType Document Type
     * @param docName name of the target Document
     * @param properties Metadata
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document createDocument(@Placement(group = "operation parameters")
    @FriendlyName("Parent document reference")
    String parentRef, @Placement(group = "operation parameters")
    @FriendlyName("Document Type")
    String docType, @Placement(group = "operation parameters")
    @FriendlyName("Name of the Document")
    String docName, @Placement(group = "operation parameters")
    Map<String, Object> properties) throws Exception {

        PropertyMap map = new PropertyMap(properties);
        return docService.createDocument(new DocRef(parentRef), docType,
                docName, map);
    }

    /**
     * Deletes a Document
     * 
     * @param ref reference of the Document to delete
     * @throws Exception
     */
    @Processor
    public void remove(@Placement(group = "operation parameters")
    String ref) throws Exception {
        docService.remove(ref);
    }

    /**
     * Copy a Document
     * 
     * @param src reference of the source document
     * @param targetParent reference of the destination document
     * @param docName name of the copied document
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document copy(@Placement(group = "operation parameters")
    String src, @Placement(group = "operation parameters")
    String targetParent, @Placement(group = "operation parameters")
    @Optional
    @Default("")
    String docName) throws Exception {
        if (docName == null || docName.isEmpty()) {
            return docService.copy(new DocRef(src), new DocRef(targetParent));
        } else {
            return docService.copy(new DocRef(src), new DocRef(targetParent),
                    docName);
        }
    }

    /**
     * Move a Document
     * 
     * @param src the reference of the document to move
     * @param targetParent the reference of thr target parent
     * @param docName the name of the document after move
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document move(@Placement(group = "operation parameters")
    String src, @Placement(group = "operation parameters")
    String targetParent, @Placement(group = "operation parameters")
    @Optional
    @Default("")
    String docName) throws Exception {
        if (docName == null || docName.isEmpty()) {
            return docService.move(new DocRef(src), new DocRef(targetParent));
        } else {
            return docService.move(new DocRef(src), new DocRef(targetParent),
                    docName);
        }
    }

    /**
     * Retrieves children of a Document
     * 
     * @param docRef Reference of the parent Document
     * @return a Documents List
     * @throws Exception
     */
    @Processor
    public Documents getChildren(@Placement(group = "operation parameters")
    String docRef) throws Exception {
        return docService.getChildren(new DocRef(docRef));
    }

    /**
     * Get a children
     * 
     * @param docRef reference of the parent Document
     * @param docName name of the child to fetch
     * @return a Document Objects
     * @throws Exception
     */
    @Processor
    public Document getChild(@Placement(group = "operation parameters")
    String docRef, @Placement(group = "operation parameters")
    String docName) throws Exception {
        return docService.getChild(new DocRef(docRef), docName);
    }

    /**
     * Get Parent Document
     * 
     * @param docRef reference of the Document
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document getParent(@Placement(group = "operation parameters")
    String docRef) throws Exception {
        return docService.getParent(new DocRef(docRef));
    }

    /**
     * Runs a NXQL Query against repository
     * 
     * @param query NXQL Query
     * @return a Documents List
     * @throws Exception
     */
    @Processor
    public Documents query(@Placement(group = "operation parameters")
    String query) throws Exception {
        return docService.query(query);
    }

    /**
     * Set Permission
     * 
     * @param doc reference of the target Document
     * @param user username or groupname to give permission to
     * @param permission permissionname
     * @param acl ACL
     * @param granted grant/deny flag
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document setPermission(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    String user, @Placement(group = "operation parameters")
    String permission, @Placement(group = "operation parameters")
    String acl, @Placement(group = "operation parameters")
    boolean granted) throws Exception {
        return docService.setPermission(new DocRef(doc), user, permission, acl,
                granted);
    }

    /**
     * Removes an ACL
     * 
     * @param doc reference of the target Document
     * @param acl ACL
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document removeAcl(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    String acl) throws Exception {
        return docService.removeAcl(new DocRef(doc), acl);
    }

    /**
     * Set Lifecycle State
     * 
     * @param doc reference to the target Document
     * @param state LifeCycle State
     * @return a Document Object
     * @throws Exceptions
     */
    @Processor
    public Document setState(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    String state) throws Exception {
        return docService.setState(new DocRef(doc), state);

    }

    /**
     * Locks a Document
     * 
     * @param doc target Document
     * @param lock lock info (can be null)
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document lock(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    String lock) throws Exception {
        if (lock == null || lock.isEmpty()) {
            return docService.lock(new DocRef(doc));
        } else {
            return docService.lock(new DocRef(doc), lock);
        }
    }

    /**
     * Unlocks a Document
     * 
     * @param doc reference to the target Document
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document unlock(@Placement(group = "operation parameters")
    String doc) throws Exception {
        return docService.unlock(new DocRef(doc));
    }

    /**
     * Change a property on a Document
     * 
     * @param doc reference to the target Document
     * @param key property Name
     * @param value property Value
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document setProperty(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    String key, @Placement(group = "operation parameters")
    String value) throws Exception {
        return docService.setProperty(new DocRef(doc), key, value);
    }

    /**
     * Remove a Property on a Document
     * 
     * @param doc reference to the target Document
     * @param key property name
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document removeProperty(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    String key) throws Exception {
        return docService.removeProperty(new DocRef(doc), key);
    }

    /**
     * Updates a Document
     * 
     * @param doc reference to the target Document
     * @param properties Map of properties to set on document
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document update(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    Map<String, Object> properties) throws Exception {
        return docService.update(new DocRef(doc), new PropertyMap(properties));
    }

    /**
     * Publish a Document
     * 
     * @param doc reference to the target Document
     * @param section reference of the publish target
     * @param override flag to control override
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document publish(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    String section, @Placement(group = "operation parameters")
    @Optional
    @Default("false")
    boolean override) throws Exception {
        return docService.publish(new DocRef(doc), new DocRef(section),
                override);
    }

    /**
     * Create a Relation
     * 
     * @param subject reference to the target Document
     * @param predicate predicate of the relation
     * @param object reference on the target related Document
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document createRelation(@Placement(group = "operation parameters")
    String subject, @Placement(group = "operation parameters")
    String predicate, @Placement(group = "operation parameters")
    DocRef object) throws Exception {
        return docService.createRelation(new DocRef(subject), predicate, object);
    }

    /**
     * get Relations
     * 
     * @param doc reference to the target Document
     * @param predicate predicate to search for
     * @param outgoing flag to indicate of relations processed must be outgoing
     *            or incoming
     * @return list of linked Document Objects
     * @throws Exception
     */
    @Processor
    public Documents getRelations(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    String predicate, @Placement(group = "operation parameters")
    boolean outgoing) throws Exception {
        return docService.getRelations(new DocRef(doc), predicate, outgoing);
    }

    /**
     * Attach a Blob to a Document
     * 
     * @param doc reference to the target Document
     * @param blob Blob to attach
     * @param xpath Xpath of the target property
     * @throws Exception
     */
    @Processor
    public void setBlob(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    FileBlob blob, @Optional
    @Default("")
    @Placement(group = "operation parameters")
    String xpath) throws Exception {

        if (xpath == null || xpath.isEmpty()) {
            docService.setBlob(new DocRef(doc), blob);
        } else {
            docService.setBlob(new DocRef(doc), blob, xpath);
        }
    }

    /**
     * Remove a Blob from a Document
     * 
     * @param doc reference to the target Document
     * @param xpath xpath of the target Blob
     * @throws Exception
     */
    @Processor
    public void removeBlob(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    @Optional
    @Default("")
    String xpath) throws Exception {

        if (xpath == null || xpath.isEmpty()) {
            docService.removeBlob(new DocRef(doc));
        } else {
            docService.removeBlob(new DocRef(doc), xpath);
        }
    }

    /**
     * get the Blob associated to a Document
     * 
     * @param doc reference to the target Document
     * @param xpath xpath of the target Blob
     * @return a FileBlob object
     * @throws Exception
     */

    @Processor
    public FileBlob getBlob(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    @Optional
    @Default("")
    String xpath) throws Exception {

        if (xpath == null || xpath.isEmpty()) {
            return docService.getBlob(new DocRef(doc));
        } else {
            return docService.getBlob(new DocRef(doc), xpath);
        }
    }

    /**
     * get the Blobs associated to a Document
     * 
     * @param doc
     * @param xpath
     * @return a list of Blobs
     * @throws Exception
     */
    // @Processor
    /*
     * public Blobs getBlobs(String doc, @Optional
     * 
     * @Default("") String xpath) throws Exception {
     * 
     * if (xpath == null || xpath.isEmpty()) { return docService.getBlobs(new
     * DocRef(doc)); } else { return docService.getBlobs(new DocRef(doc),
     * xpath); } }
     */

    /**
     * Creates a version
     * 
     * @param doc reference to the target Document
     * @param increment increment policy (minor/major)
     * @return a Document Object
     * @throws Exception
     */
    @Processor
    public Document createVersion(@Placement(group = "operation parameters")
    String doc, @Placement(group = "operation parameters")
    @Optional
    @Default("")
    String increment) throws Exception {

        if (increment == null || increment.isEmpty()) {
            return docService.createVersion(new DocRef(doc));
        } else {
            return docService.createVersion(new DocRef(doc), increment);
        }
    }

    /**
     * Fire an Event
     * 
     * @param event name of the event to raise
     * @param doc reference to the document to attach to the event
     * @throws Exception
     */
    @Processor
    public void fireEvent(@Placement(group = "operation parameters")
    String event, @Placement(group = "operation parameters")
    @Optional
    @Default("")
    String doc) throws Exception {
        if (doc == null || doc.isEmpty()) {
            docService.fireEvent(event);
        } else {
            docService.fireEvent(new DocRef(doc), event);
        }
    }

    /**
     * Executes an arbitrary operation
     * 
     * @param operationName Name of the Automation Operation
     * @param input Input of the Operation
     * @param params Parameters of the Operation
     * @return Result of the Operation
     * @throws Exception
     */
    @Processor
    public Object runOperation(@Placement(group = "operation parameters")
    String operationName, @Placement(group = "operation parameters")
    @Optional
    Object input, @Optional
    @Placement(group = "operation parameters")
    Map<String, String> params) throws Exception {
        OperationRequest request = session.newRequest(operationName);
        OperationDocumentation opDef = request.getOperation();

        // fill operation parameter according to signature
        for (Param param : opDef.getParams()) {
            for (String pname : params.keySet()) {
                if (pname.equals(param.getName())) {
                    request.set(pname, params.get(pname));
                    break;
                }
            }
        }

        if (input != null) {
            String[] sig = opDef.getSignature();
            for (int i = 0; i < sig.length; i = i + 2) {
                String inputType = sig[i];
                if (inputType.equals("Document")) {
                    request.setInput(new DocRef(input.toString()));
                } else if (inputType.equals("Blob")) {
                    if (input instanceof File) {
                        request.setInput(new FileBlob((File) input));
                    }
                }
            }
        }
        return request.execute();
    }

    /**
     * @Mime(MimeTypes.JSON)
     * @Transformer(sourceTypes = { Document.class }) public static String
     *                          documentToJSON(Document doc) {
     * 
     *                          return null; }
     **/

    /**
     * Creates a Blob from a File
     * 
     * @param file the input File
     * @return the Blob wrapping the File
     */
    @Transformer(sourceTypes = { File.class })
    public static FileBlob fileToBlob(File file) {
        return new FileBlob(file);
    }

    /**
     * Creates a Blob from a String
     * 
     * @param file the input String
     * @return the Blob wrapping the String
     */
    @Transformer(sourceTypes = { String.class })
    public static StringBlob stringToBlob(String input) {
        return new StringBlob(input);
    }

    /**
     * Convert a Document to a Simple Map
     * 
     * @param doc the Document to convert
     * @return the resulting Map<String, Object>
     */
    @Transformer(sourceTypes = { Document.class })
    public static Map<String, Object> documentToMap(Document doc) {
        Map<String, Object> map = doc.getProperties().map();
        map.put("type", doc.getType());
        map.put("facets", doc.getFacets().list());
        map.put("id", doc.getId());
        map.put("lock", doc.getLock());
        map.put("lockCreated", doc.getLockCreated());
        map.put("lockOwner", doc.getLockOwner());
        map.put("path", doc.getPath());
        map.put("repository", doc.getRepository());
        map.put("state", doc.getState());
        return map;
    }

    /**
     * Converts a list of Documents into a simple list of Map
     * 
     * @param docs the Documents list to convert
     * @return the resulting List of Map
     */
    @Transformer(sourceTypes = { Documents.class })
    public static List<Map<String, Object>> documentsToListOfMap(Documents docs) {
        List<Map<String, Object>> result = new ArrayList<Map<String, Object>>();
        for (Document doc : docs) {
            result.add(documentToMap(doc));
        }
        return result;
    }

}
